apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartprepai-deployment
  labels:
    app: smartprepai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smartprepai
  template:
    metadata:
      labels:
        app: smartprepai
    spec:
      containers:
      - name: smartprepai
        image: smartprepai:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: smartprepai-secrets
              key: groq-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
